<?php
include("Database.php");
/**
 * @Migration Schema classes
 * Do not edit this file as this may break your application
 */
class DatabaseSchema {
    private $name;
    private $db;
    

    public function __construct($dbname) {
        $this->name = $dbname;
        $d = new Database("schema");
        $this->db = $d->db;
    }

    public function migrate(){
        try {
            $sql = "CREATE DATABASE ".$this->name;
            $this->db->exec($sql);
            echo "Database ".$this->name. " migration successful";
        }
        catch (PDOException $error) {
            echo "Error in migration:\n".$error->getMessage();
        }
    }
}

class TableSchema{
    private $db;
    private $name;
    private $structure;

    public function __construct($table_name, $structure) {
        $this->name = $table_name; 
        $this->structure = $structure;
        $d = new Database("schema");
        $this->db = $d->db;
    }

    public function migrate(){
        $keys = array_keys($this->structure);
        if (in_array("id", $keys)) {
            echo "Error in migration:\nColumn id should not be included in table structure";
        }
        else{
            $base = "CREATE TABLE ".$this->name. "(id INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,";
            for ($i=0; $i < count($keys); $i++) { 
                $col = $this->structure[$keys[$i]];
                $n = ($col["null"] === true) ? "" : "NOT NULL";
                $len = (!$col["length"]) ? "" : "(".$col["length"].") ";
                $str = $keys[$i]." ".strtoupper($col["type"]).$len.$n;
                if ($i !== (count($keys) - 1)) {
                    $str .= ",";
                }
                $base .= $str;
            }
            $base .= ")";

            try {
                $sql = $base;
                $this->db->exec($sql);
                echo "Table ".$this->name. " migration successful";
            }
            catch (PDOException $error) {
                echo "Error in migration:\n".$error->getMessage();
            }
            
        }
    }
}

class ActionSchema{
    private $db;
    private $structure;

    public function __construct($structure) {
        $d = new Database("schema");
        $this->db = $d->db;
        $this->structure = $structure;
    }

    public function migrate(){
       $base = "";

        if (strtoupper($this->structure["action"]) == "TRUNCATE") {
            $action = strtoupper($this->structure["action"]);
            $target = $this->structure["target"];
            $base = "TRUNCATE TABLE ".$target;
        }
        elseif (strtoupper($this->structure["action"]) == "ALTER" && strtoupper($this->structure["target_type"]) == "DATABASE" && strtoupper($this->structure["action_type"]) == "DROP") {
            $target = $this->structure["target"];
            $base = "DROP DATABASE ".$target;
        }
        elseif (strtoupper($this->structure["action"]) == "ALTER" && strtoupper($this->structure["target_type"]) == "TABLE" && strtoupper($this->structure["action_type"]) == "DROP") {
            $target = $this->structure["target"];
            $base = "DROP TABLE ".$target;
        }
        else {
            $target = $this->structure["target"];
            $target_type = strtoupper($this->structure["target_type"]);
            $action_type = strtoupper($this->structure["action_type"]);
            $object = $this->structure["data"];
            $base = "ALTER TABLE ".$target;
            if ($action_type == "drop") {
                $base .= " DROP ".$target_type." ".$object["column"];
            }
            else {
                $base .= " ".$action_type." ".$object["column"]." ".$object["data_type"];
            }
        }

        try {
            $sql = $base;
            $this->db->exec($sql);
            echo "Actions schema migration successful";
        }
        catch (PDOException $error) {
            echo "Error in migration:\n".$error->getMessage();
        }
    }
}

?>